/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'oelprince' at '6/19/16 8:38 AM' with Gradle 2.13
 *
 * @author oelprince, @date 6/19/16 8:38 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
